//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BCGPSymbolizer.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_MAIN_TOOLBAR                101
#define IDD_FORMVIEW_RASTERSYMBOLIZER   102
#define IDD_FORMVIEW_LINESYMPOLIZER     103
#define IDS_WINDOWS_MANAGER             107
#define IDR_MAINFRAME                   128
#define IDR_BCGPSymbolizerTYPE          129
#define IDR_CONTEXT_MENU                130
#define IDR_POPUP_TOOLBAR               131
#define IDR_POPUP_MDITABS               132
#define IDR_POPUP_DROP_MDITABS          133
#define IDB_WORKSPACE                   147
#define IDB_TOOLBAR_HC                  151
#define IDB_TOOLS_PAGE1                 167
#define IDB_TOOLS_PAGE2                 168
#define IDD_FORMVIEW_LINEPATTERNSYMPOLIZER 170
#define IDD_FORMVIEW_POINTSYMBOLIZER    171
#define IDD_FORMVIEW_DOTSYMBOLIZER      172
#define IDI_ICON_RESET                  176
#define IDC_COMPANY_URL                 1041
#define IDC_LIST_DLGBAR                 1048
#define IDC_STATIC_DLGBAR               1049
#define IDC_CHECK_DLGBAR                1050
#define IDC_CHECK_DEFAULT_LINE          1051
#define IDC_MFCCOLORBUTTON_LINE         1052
#define IDC_STATIC_COLOR                1053
#define IDC_EDIT_WIDTH_LINE             1054
#define IDC_EDIT_OPACITY_LINE           1055
#define IDC_COMBO_JOIN_LINE             1056
#define IDC_COMBO_CAP_LINE              1057
#define IDC_EDIT_GAMMA_LINE             1058
#define IDC_COMBO_GAMMA_METHOD_LINE     1059
#define IDC_EDIT_DASHARRAY_LINE         1060
#define IDC_EDIT_DASHOFFSET_LINE        1062
#define IDC_EDIT_MITERLIMIT_LINE        1063
#define IDC_CHECK_CLIP_LINE             1064
#define IDC_EDIT_SIMPLIFY_LINE          1066
#define IDC_COMBO_SIMPLIFY_LINE         1067
#define IDC_EDIT_SMOOTH_LINE            1068
#define IDC_EDIT_OFFSET_LINE            1069
#define IDC_RASTERIZER_LINE             1070
#define IDC_COMBO_COMP_OP_LINE          1073
#define IDC_EDIT6                       1096
#define IDC_EDIT_GEOMETRY_TRANSFORM_LINE 1100
#define IDC_EDIT_XML_LINE               1101
#define IDC_COMBO_LINEPATTERN_TYPE      1102
#define IDC_EDIT_FILE_LINEPATTERN       1103
#define IDC_EDIT_WIDTH_LINEPATTERN      1104
#define IDC_EDIT_OPACITY_LINEPATTERN    1105
#define IDC_COMBO_JOIN_LINEPATTERN      1106
#define IDC_COMBO_CAP_LINEPATTERN       1107
#define IDC_EDIT_DASHARRAY_LINEPATTERN  1108
#define IDC_EDIT_MITERLIMIT_LINEPATTERN 1110
#define IDC_CHECK_CLIP_LINEPATTERN      1111
#define IDC_CHECK_DEFAULT_LINEPATTERN   1112
#define IDC_EDIT_SIMPLIFY_LINEPATTERN   1113
#define IDC_COMBO_SIMPLIFY_LINEPATTERN  1114
#define IDC_EDIT_SMOOTH_LINEPATTERN     1115
#define IDC_EDIT_OFFSET_LINEPATTERN     1116
#define IDC_ALIGNMENT_LINEPATTERN       1117
#define IDC_EDIT_GEOMETRY_TRANSFORM_LINEPATTERN 1118
#define IDC_EDIT_TRANSFORM_LINEPATTERN  1120
#define IDC_COMBO_COMP_OP_LINEPATTERN   1121
#define IDC_EDIT_XML_LINEPATTERN        1122
#define IDC_CHECK_DEFAULT_RASTER        1124
#define IDC_MFCCOLORBUTTON_RASTER       1125
#define IDC_EDIT_OPACITY_RASTER         1126
#define IDC_EDIT_FILTERFACTOR_RASTER    1127
#define IDC_COMBO_SCALING_RASTER        1128
#define IDC_EDIT_MESHSIZE_RASTER        1129
#define IDC_COMBO_COMP_OP_RASTER        1130
#define IDC_COMBO_DEFAULTMODE_RASTER    1131
#define IDC_EDIT_EPSILON_RASTER         1132
#define IDC_EDIT_STOP_RASTER            1133
#define IDC_EDIT_XML_RASTER             1134
#define IDC_CHECK_DEFAULT_POINT         1135
#define IDC_EDIT_FILE_POINT             1136
#define IDC_EDIT_OPACITY_POINT          1138
#define IDC_CHECK_ALLOWOVERLAP_POINT    1139
#define IDC_CHECK_IGNORE_POINT          1140
#define IDC_COMBO_PLACEMENT_POINT       1141
#define IDC_COMBO_COMP_OP_POINT         1142
#define IDC_COMBO_TRANSFORM_POINT       1143
#define IDC_EDIT_XML_POINT              1144
#define IDC_EDIT_TRANSFORM_POINT        1145
#define IDC_CHECK_DEFAULT_DOT           1146
#define IDC_MFCCOLORBUTTON_DOT          1147
#define IDC_EDIT_HEIGHT_DOT             1148
#define IDC_EDIT_OPACITY_DOT            1149
#define IDC_COMBO_COMP_OP_DOT           1150
#define IDC_EDIT_XML_DOT                1151
#define IDC_EDIT_WIDTH_DOT              1153
#define IDC_STATIC_RESET_LINEPATTERN    1154
#define IDC_STATIC_RESET_LINE           1155
#define IDC_STATIC_FILE_LINEPATTERN     1155
#define IDC_STATIC_FILE_POINT           1156
#define IDC_STATIC_RESET_POINT          1157
#define IDC_STATIC_RESET_RASTER         1158
#define IDC_STATIC_RESET_DOT            1159
#define IDC_COMBO1                      1160
#define ID_VIEW_CUSTOMIZE               32770
#define ID_VIEW_TOOLBARS                32771
#define ID_VIEW_WORKSPACE               32791
#define ID_VIEW_WORKSPACE2              32792
#define ID_VIEW_USER_TOOLBAR1           32793
#define ID_VIEW_USER_TOOLBAR2           32794
#define ID_VIEW_USER_TOOLBAR3           32795
#define ID_VIEW_USER_TOOLBAR4           32796
#define ID_VIEW_USER_TOOLBAR5           32797
#define ID_VIEW_USER_TOOLBAR6           32798
#define ID_VIEW_USER_TOOLBAR7           32799
#define ID_VIEW_USER_TOOLBAR8           32800
#define ID_VIEW_USER_TOOLBAR9           32801
#define ID_VIEW_USER_TOOLBAR10          32802
#define ID_VIEW_OUTPUT                  32803
#define ID_WINDOW_MANAGER               32825
#define ID_VIEW_APPLOOK                 32826
#define ID_VIEW_PROPERTIES              32827
#define ID_MDI_NEW_VERT_GROUP           32828
#define ID_MDI_NEW_HORZ_TAB_GROUP       32829
#define ID_MDI_MOVE_TO_PREV_GROUP       32830
#define ID_MDI_CANCEL                   32831
#define ID_MDI_MOVE_TO_NEXT_GROUP       32832
#define ID_VIEW_TOOLBOX                 32858
#define ID_TOOLBOX                      32859
#define ID_VIEW_WORKSPACE3              32860
#define ID_VIEW_WORKSPACE4              32861
#define ID_VIEW_WORKSPACE5              32862

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        177
#define _APS_NEXT_COMMAND_VALUE         32860
#define _APS_NEXT_CONTROL_VALUE         1161
#define _APS_NEXT_SYMED_VALUE           117
#endif
#endif
